### ISSUE TITLE
Pause background audio when app is in background

### ISSUE THREAD

**Issue by ryansunxl** [intel/cordova-plugin-intel-xdk-player#1]
Thanks for the plugin, very useful!
When I use this plugin to play a background mp3 file in an android app with startAudio, the music won't stop if the app is switched to background, can we fix it in this plugin? or we have to pause it manually?

**Comment by xmnboy** [comment]
Your app should be the one to decide what the proper behavior is when it goes to the background. So I would recommend that your app pause the playback on the switch to background and then resume (if appropriate) on the resume to foreground. Trying to modify the plugin to anticipate all application needs is an impossible task.
